# Generated by Django 5.2.6 on 2025-09-29 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('sales', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='payment_status',
            field=models.CharField(choices=[('no_pagada', 'No pagada'), ('parcial', 'Pago parcial'), ('pagada', 'Pagada')], db_index=True, default='no_pagada', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['payment_status'], name='sales_venta_payment_d37a96_idx'),
        ),
    ]
