# Generated by Django 5.2.6 on 2025-09-29 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('sales', '0002_venta_payment_status_alter_venta_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('valido_desde', models.DateField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('order', 'Por venta'), ('item', 'Por ítem')], default='order', max_length=10)),
                ('mode', models.CharField(choices=[('percent', '%'), ('amount', 'Monto')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stackable', models.BooleanField(default=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=10)),
                ('payment_method_code', models.CharField(blank=True, default='', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='org.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='org.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'Venta'), ('item', 'Ítem')], max_length=10)),
                ('mode', models.CharField(choices=[('percent', '%'), ('amount', 'Monto')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('promo', 'Promoción'), ('payment', 'Método de pago')], default='manual', max_length=10)),
                ('motivo', models.CharField(blank=True, default='', max_length=160)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='sales.ventaitem')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='sales.promotion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='sales.venta')),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['empresa', 'sucursal', 'activo'], name='sales_promo_empresa_30d5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesadjustment',
            index=models.Index(fields=['venta', 'kind'], name='sales_sales_venta_i_453031_idx'),
        ),
    ]
