# Generated by Django 5.2.6 on 2025-09-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_promotion_salesadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
