# Generated by Django 5.2.6 on 2025-09-30 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_promotion_descripcion_promotion_min_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesadjustment',
            index=models.Index(fields=['venta', 'promotion'], name='sales_sales_venta_i_f56e51_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('promotion__isnull', False)), fields=('venta', 'promotion', 'item'), name='uq_salesadj_unique_promo_per_target'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'order'), ('item__isnull', True)), models.Q(('kind', 'item'), ('item__isnull', False)), _connector='OR'), name='ck_salesadj_kind_item_consistency'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'percent'), ('value__gte', 0), ('value__lte', 100)), models.Q(('mode', 'amount'), ('value__gte', 0)), _connector='OR'), name='ck_salesadj_value_range_by_mode'),
        ),
    ]
