# Generated by Django 5.2.6 on 2025-09-30 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesadjustment_sales_sales_venta_i_f56e51_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesadjustment',
            name='uq_salesadj_unique_promo_per_target',
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('item__isnull', True), ('promotion__isnull', False)), fields=('venta', 'promotion'), name='uq_salesadj_unique_promo_order'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('item__isnull', False), ('promotion__isnull', False)), fields=('venta', 'item', 'promotion'), name='uq_salesadj_unique_promo_item'),
        ),
    ]
