# Generated by Django 5.2.6 on 2025-10-05 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_turnocaja_turnocajatotal_and_more'),
        ('customers', '0001_initial'),
        ('org', '0006_add_cashbox_policy_to_empresa'),
        ('sales', '0006_remove_salesadjustment_uq_salesadj_unique_promo_per_target_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno operativo asignado al crear la venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='cashbox.turnocaja'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=20),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['turno'], name='sales_venta_turno_i_11d780_idx'),
        ),
    ]
