# Generated by Django 5.2.6 on 2025-09-13 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Monto positivo, hasta 2 decimales.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('vigencia_inicio', models.DateField(help_text='Fecha de inicio de vigencia (incluida).', verbose_name='Vigente desde')),
                ('vigencia_fin', models.DateField(blank=True, help_text='Opcional. Dejar vacío para vigencia abierta.', null=True, verbose_name='Vigente hasta')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='org.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalog.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='org.sucursal')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='vehicles.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Precio de servicio',
                'verbose_name_plural': 'Precios de servicio',
                'indexes': [models.Index(fields=['empresa', 'sucursal', 'servicio', 'tipo_vehiculo', 'vigencia_inicio'], name='pricing_idx_comb_inicio'), models.Index(fields=['empresa', 'sucursal', 'servicio', 'tipo_vehiculo', 'vigencia_fin'], name='pricing_idx_comb_fin'), models.Index(fields=['empresa', 'activo', 'vigencia_fin'], name='pricing_idx_estado')],
                'constraints': [models.CheckConstraint(condition=models.Q(('vigencia_fin__isnull', True), ('vigencia_fin__gte', models.F('vigencia_inicio')), _connector='OR'), name='pricing_chk_fin_ge_inicio'), models.UniqueConstraint(fields=('empresa', 'sucursal', 'servicio', 'tipo_vehiculo', 'vigencia_inicio'), name='pricing_unq_misma_combinacion_mismo_inicio'), models.UniqueConstraint(condition=models.Q(('activo', True), ('vigencia_fin__isnull', True)), fields=('empresa', 'sucursal', 'servicio', 'tipo_vehiculo'), name='pricing_unq_abierto_activo_por_combinacion')],
            },
        ),
    ]
