# Generated by Django 5.2.6 on 2025-09-21 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamembership',
            name='sucursal_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='org.sucursal'),
        ),
    ]
