# Generated by Django 5.2.6 on 2025-09-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresamembership_sucursal_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamembership',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresamembership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresamembership',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
