$BASE = "lavaderosapp"

# Crear carpetas
New-Item -ItemType Directory -Force -Path "$BASE\templates\includes"
New-Item -ItemType Directory -Force -Path "$BASE\templates\account"
New-Item -ItemType Directory -Force -Path "$BASE\templates\errors"
New-Item -ItemType Directory -Force -Path "$BASE\static\css\bootswatch"
New-Item -ItemType Directory -Force -Path "$BASE\static\js"
New-Item -ItemType Directory -Force -Path "$BASE\static\img"
New-Item -ItemType Directory -Force -Path "$BASE\static\vendor"
New-Item -ItemType Directory -Force -Path "$BASE\media"
New-Item -ItemType Directory -Force -Path "$BASE\staticfiles"

# Crear archivos vacíos
New-Item -ItemType File -Force -Path "$BASE\templates\base.html"
New-Item -ItemType File -Force -Path "$BASE\templates\includes\_navbar.html"
New-Item -ItemType File -Force -Path "$BASE\templates\includes\_messages.html"
New-Item -ItemType File -Force -Path "$BASE\templates\includes\_footer.html"
New-Item -ItemType File -Force -Path "$BASE\templates\includes\_pagination.html"
New-Item -ItemType File -Force -Path "$BASE\templates\account\login.html"
New-Item -ItemType File -Force -Path "$BASE\templates\account\signup.html"
New-Item -ItemType File -Force -Path "$BASE\templates\errors\401.html"
New-Item -ItemType File -Force -Path "$BASE\templates\errors\403.html"
New-Item -ItemType File -Force -Path "$BASE\templates\errors\404.html"
New-Item -ItemType File -Force -Path "$BASE\templates\errors\500.html"
New-Item -ItemType File -Force -Path "$BASE\static\css\bootstrap.min.css"
New-Item -ItemType File -Force -Path "$BASE\static\css\app.css"
New-Item -ItemType File -Force -Path "$BASE\static\css\bootswatch\flatly.min.css"
New-Item -ItemType File -Force -Path "$BASE\static\js\bootstrap.bundle.min.js"
New-Item -ItemType File -Force -Path "$BASE\static\js\app.js"
New-Item -ItemType File -Force -Path "$BASE\static\img\logo.png"
