# Generated by Django 5.2.6 on 2025-09-21 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('payments', '0003_alter_mediopago_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abierto_en', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha/hora de apertura del cierre.')),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Fecha/hora de cierre. Vacío mientras el cierre está abierto.', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas operativas del cierre (diferencias, observaciones, etc.).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_por', models.ForeignKey(blank=True, help_text='Usuario que cerró el cierre (si corresponde).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cerrados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece el cierre.', on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='org.empresa')),
                ('sucursal', models.ForeignKey(help_text='Sucursal donde se realizó el cierre.', on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='org.sucursal')),
                ('usuario', models.ForeignKey(help_text='Usuario que abrió el cierre (cajero/operador).', on_delete=django.db.models.deletion.PROTECT, related_name='cierres_abiertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ('-abierto_en', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='CierreCajaTotal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('propinas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cierre', models.ForeignKey(help_text='Cierre de caja asociado.', on_delete=django.db.models.deletion.CASCADE, related_name='totales', to='cashbox.cierrecaja')),
                ('medio', models.ForeignKey(help_text='Método de pago.', on_delete=django.db.models.deletion.PROTECT, related_name='totales_cierre', to='payments.mediopago')),
            ],
            options={
                'verbose_name': 'Total por Método',
                'verbose_name_plural': 'Totales por Método',
            },
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['empresa', 'sucursal', 'abierto_en'], name='cashbox_cie_empresa_c286ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['empresa', 'abierto_en'], name='cashbox_cie_empresa_6a4b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrado_en__isnull', True)), fields=('sucursal',), name='uniq_cierre_abierto_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.CheckConstraint(condition=models.Q(('cerrado_en__isnull', True), ('cerrado_en__gte', models.F('abierto_en')), _connector='OR'), name='ck_cierre_cerrado_en_ge_abierto_en'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.CheckConstraint(condition=models.Q(('empresa__isnull', False), ('sucursal__isnull', False)), name='ck_cierre_empresa_sucursal_not_null'),
        ),
        migrations.AddIndex(
            model_name='cierrecajatotal',
            index=models.Index(fields=['cierre', 'medio'], name='cashbox_cie_cierre__ace97b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cierrecajatotal',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', Decimal('0.00')), ('propinas__gte', Decimal('0.00'))), name='ck_totales_no_negativos'),
        ),
    ]
