# Generated by Django 5.2.6 on 2025-09-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecajatotal',
            options={'ordering': ('-creado_en',), 'verbose_name': 'Total por Método', 'verbose_name_plural': 'Totales por Método'},
        ),
    ]
