# Generated by Django 5.2.6 on 2025-10-05 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_alter_cierrecajatotal_options'),
        ('org', '0006_add_cashbox_policy_to_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierto_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('responsable_nombre', models.CharField(help_text='Nombre del responsable del turno (libre)', max_length=120)),
                ('cerrado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('monto_contado_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abierto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='org.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='org.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoCajaTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_nombre', models.CharField(max_length=50)),
                ('monto_teorico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('propinas_teoricas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_contado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('propinas_contadas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dif_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dif_propinas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales', to='cashbox.turnocaja')),
            ],
            options={
                'ordering': ['medio_nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['empresa', 'sucursal', 'abierto_en'], name='cashbox_tur_empresa_a58ed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrado_en__isnull', True)), fields=('sucursal',), name='uniq_turno_abierto_por_sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='turnocajatotal',
            unique_together={('turno', 'medio_nombre')},
        ),
    ]
