# Generated by Django 5.2.6 on 2025-09-25 03:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False, help_text='Si está activo y marcado como default, se asigna a empresas nuevas.')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Días de prueba gratuitos al crear la suscripción (0 = sin trial).')),
                ('max_empresas_por_usuario', models.PositiveIntegerField(default=1, help_text='Cuántas empresas puede crear/poseer un usuario (owner).')),
                ('max_sucursales_por_empresa', models.PositiveIntegerField(default=1)),
                ('max_usuarios_por_empresa', models.PositiveIntegerField(default=5, help_text='Membresías activas (EmpresaMembership) en la empresa.')),
                ('max_empleados_por_sucursal', models.PositiveIntegerField(default=5, help_text='Membresías activas asignadas a una sucursal específica.')),
                ('max_storage_mb', models.PositiveIntegerField(default=200)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('external_plan_id', models.CharField(blank=True, help_text='ID del plan en la pasarela (ej. preapproval plan de Mercado Pago).', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan SaaS',
                'verbose_name_plural': 'Planes SaaS',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionSaaS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('suspendida', 'Suspendida')], default='activa', max_length=20)),
                ('inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fin', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('past_due', 'Past due')], default='unpaid', help_text='trial/paid/unpaid/past_due para UI y conciliación.', max_length=20)),
                ('external_customer_id', models.CharField(blank=True, help_text='ID del cliente en la pasarela (ej. Mercado Pago).', max_length=120)),
                ('external_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción/adhesión en la pasarela.', max_length=120)),
                ('external_plan_id', models.CharField(blank=True, help_text='Plan/code en la pasarela (útil si difiere del de PlanSaaS).', max_length=120)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(help_text='Relación 1:1 en MVP. Futuro: mover histórico a otra tabla si se requiere.', on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='org.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='saas.plansaas')),
            ],
            options={
                'verbose_name': 'Suscripción SaaS',
                'verbose_name_plural': 'Suscripciones SaaS',
                'indexes': [models.Index(fields=['estado'], name='saas_suscri_estado_483126_idx'), models.Index(fields=['payment_status'], name='saas_suscri_payment_b86d12_idx')],
            },
        ),
    ]
