# Generated by Django 5.2.6 on 2025-09-14 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del pago (UUID).', primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('qr_mp', 'QR / MercadoPago')], help_text='Método de pago utilizado.', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago. Debe ser mayor a 0.', max_digits=12)),
                ('es_propina', models.BooleanField(default=False, help_text='Si el pago corresponde a una propina.')),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa del pago (ej. ID de transacción bancaria o de pasarela).', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas relacionadas al pago.', null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Clave de idempotencia para evitar pagos duplicados (ej. token de pasarela).', max_length=64, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización.')),
                ('creado_por', models.ForeignKey(help_text='Usuario que registró el pago.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(help_text='Venta a la que se asocia este pago.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('venta', 'idempotency_key'), name='unique_pago_idempotency_per_venta')],
            },
        ),
    ]
