# Generated by Django 5.2.6 on 2025-09-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('payments', '0002_mediopago'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Medio de pago', 'verbose_name_plural': 'Medios de pago'},
        ),
        migrations.AlterUniqueTogether(
            name='mediopago',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
        migrations.AddField(
            model_name='pago',
            name='medio',
            field=models.ForeignKey(default=1, help_text='Medio de pago utilizado.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.mediopago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está disponible para usar en la caja.'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece este medio de pago.', on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='org.empresa'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='nombre',
            field=models.CharField(help_text='Nombre visible del medio de pago.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Clave de idempotencia para evitar pagos duplicados.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia externa (ID de transacción, cupón, etc.).', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['creado_en'], name='payments_pa_creado__a5e550_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['venta', 'es_propina'], name='payments_pa_venta_i_c4d009_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediopago',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_medio_pago_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_gt_0'),
        ),
    ]
