# Generated by Django 5.2.6 on 2025-10-05 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_turnocaja_turnocajatotal_and_more'),
        ('payments', '0003_alter_mediopago_options_and_more'),
        ('sales', '0006_remove_salesadjustment_uq_salesadj_unique_promo_per_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno operativo en el momento del pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cashbox.turnocaja'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['turno'], name='payments_pa_turno_i_f9788f_idx'),
        ),
    ]
