# Generated by Django 5.2.6 on 2025-09-12 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='El tipo pertenece a la empresa (multi-tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_vehiculo', to='org.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=60)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('patente', models.CharField(help_text='Ej.: ABC123 o AB123CD', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Propietario del vehículo.', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='customers.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='org.empresa')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='vehicles.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-actualizado', 'patente'],
            },
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['empresa', 'slug'], name='vehicles_ti_empresa_1b50d7_idx'),
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['empresa', 'activo'], name='vehicles_ti_empresa_d0d237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipovehiculo',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'patente'], name='vehicles_ve_empresa_b8b2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'cliente'], name='vehicles_ve_empresa_5cdcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['activo'], name='vehicles_ve_activo_eb1d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'patente'), name='uniq_patente_por_empresa_activos'),
        ),
    ]
