# Generated by Django 5.2.6 on 2025-09-21 12:51

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='public_expires_at',
            field=models.DateTimeField(blank=True, help_text='Opcional: fecha/hora de expiración del link público.', null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='public_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token público no adivinable para compartir el comprobante sin login.', unique=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='public_revocado',
            field=models.BooleanField(default=False, help_text='Si está en True, el link público queda inválido.'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['empresa', 'emitido_en'], name='idx_inv_emp_fecha'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['public_key'], name='idx_inv_public_key'),
        ),
    ]
