# Generated by Django 5.2.6 on 2025-09-08 01:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='creado',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='actualizado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subdominio',
            field=models.SlugField(default=1, help_text="Solo minúsculas, números y guiones (ej. 'lavadero-norte').", max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='org.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo_interno', models.CharField(help_text='Código del ERP', max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='org.empresa')),
            ],
            options={
                'ordering': ['empresa__nombre', 'nombre'],
                'unique_together': {('empresa', 'codigo_interno')},
            },
        ),
    ]
