# Generated by Django 5.2.6 on 2025-09-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('suspended', 'Suspendida')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subdominio',
            field=models.SlugField(max_length=63, unique=True),
        ),
    ]
