# Generated by Django 5.2.6 on 2025-09-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_empresa_options_empresa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida')], default='active', max_length=16),
        ),
    ]
