# Generated by Django 5.2.6 on 2025-09-09 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_empresa_trial_ends_at_empresa_trial_started_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='empresaconfig',
            options={'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuraciones de Empresa'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='empresaconfig',
            old_name='data',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='trial_ends_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='trial_started_at',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='activo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='clave',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='subdominio',
            field=models.SlugField(help_text='Identificador único en la URL (ej: misucursal.lavaderosapp.com)', unique=True, verbose_name='Subdominio'),
        ),
        migrations.AlterField(
            model_name='empresaconfig',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='org.empresa'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_interno',
            field=models.CharField(help_text='Código único dentro de la empresa', max_length=20, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='empresaconfig',
            unique_together={('empresa', 'clave')},
        ),
    ]
