# Generated by Django 5.2.6 on 2025-10-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cashbox_policy',
            field=models.CharField(choices=[('STRICT', 'Strict (ventas y pagos requieren caja)'), ('PAYMENTS_ONLY', 'Solo pagos requieren caja'), ('BY_METHOD', 'Por medio de pago (granular)')], default='PAYMENTS_ONLY', help_text='Política de caja: STRICT (ventas y pagos), PAYMENTS_ONLY (solo pagos), BY_METHOD (según medio).', max_length=20),
        ),
    ]
