# Generated by Django 5.2.6 on 2025-09-15 01:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('empresa_id', models.CharField(blank=True, db_index=True, help_text='ID de la empresa (tenant) en texto.', max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='ID del usuario autenticado (si aplica).', max_length=64, null=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Username del usuario (si aplica).', max_length=150, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='X-Request-ID (UUID string).', max_length=36, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='ID de correlación transversal (opcional).', max_length=36, null=True)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('origen', models.CharField(db_index=True, help_text='Logger/módulo: ej. "http", "payments.services", "django.request".', max_length=120)),
                ('evento', models.CharField(db_index=True, help_text='Etiqueta corta: ej. "access_log", "unhandled_exception", "django_log".', max_length=80)),
                ('mensaje', models.TextField(help_text='Mensaje breve/útil para lectura humana.')),
                ('http_method', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('http_path', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('http_status', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, db_index=True, help_text='Duración del request (ms).', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log de aplicación',
                'verbose_name_plural': 'Logs de aplicación',
                'db_table': 'app_log',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en', 'nivel', 'http_status'], name='app_log_creado__ca8fbd_idx'), models.Index(fields=['empresa_id', 'origen', 'evento'], name='app_log_empresa_80c7cc_idx'), models.Index(fields=['request_id'], name='app_log_request_f430f1_idx'), models.Index(fields=['http_path'], name='app_log_http_pa_80b39b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('empresa_id', models.CharField(blank=True, db_index=True, help_text='ID de la empresa (tenant) en texto.', max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='ID del usuario que ejecuta la acción.', max_length=64, null=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Username del usuario (si aplica).', max_length=150, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='X-Request-ID para correlación.', max_length=36, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(db_index=True, help_text='Etiqueta "<app_label>.<ModelName>": ej. "sales.Venta".', max_length=120)),
                ('resource_id', models.CharField(db_index=True, help_text='ID del recurso afectado (UUID/int/str).', max_length=120)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=20)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('reason', models.TextField(blank=True, help_text='Motivo/justificación del cambio (opcional).', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Diferencias por campo: {"campo": {"before": ..., "after": ...}}.')),
                ('snapshot_before', models.JSONField(blank=True, default=dict, help_text='Estado previo serializado.')),
                ('snapshot_after', models.JSONField(blank=True, default=dict, help_text='Estado posterior serializado.')),
            ],
            options={
                'verbose_name': 'Auditoría de negocio',
                'verbose_name_plural': 'Auditorías de negocio',
                'db_table': 'audit_log',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en', 'empresa_id'], name='audit_log_creado__6dfb88_idx'), models.Index(fields=['resource_type', 'resource_id', '-creado_en'], name='audit_log_resourc_b8d12e_idx'), models.Index(fields=['action', '-creado_en'], name='audit_log_action_b19418_idx')],
            },
        ),
    ]
