# Generated by Django 5.2.6 on 2025-09-13 03:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio (p. ej., Lavado exterior, Encerado).', max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Identificador URL-safe; si se deja vacío se genera automáticamente.', max_length=140, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción breve u observaciones del servicio (opcional).', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está desmarcado, el servicio no aparece para nuevas ventas/precios.', verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('empresa', models.ForeignKey(help_text='Empresa (tenant) a la que pertenece el servicio.', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='org.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': [django.db.models.functions.text.Lower('nombre'), 'id'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='svc_empresa_activo_idx'), models.Index(fields=['empresa', 'nombre'], name='svc_empresa_nombre_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('empresa'), name='uniq_servicio_nombre_ci_por_empresa'), models.UniqueConstraint(fields=('empresa', 'slug'), name='uniq_servicio_slug_por_empresa')],
            },
        ),
    ]
