# Generated by Django 5.2.6 on 2025-10-03 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('org', '0005_alter_empresa_options_alter_empresaconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Alias visible, p. ej. 'Cuenta Gmail Administración'", max_length=120)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS (común en 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='SSL implícito (común en 465)')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('remitente_por_defecto', models.CharField(blank=True, default='', help_text="Ej: 'Mi Empresa <info@dominio.com>'", max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_servers', to='org.empresa')),
            ],
            options={
                'verbose_name': 'Servidor de Email (SMTP)',
                'verbose_name_plural': 'Servidores de Email (SMTP)',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
